# Generated by Django 3.0.6 on 2020-05-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('gender', models.CharField(choices=[('1', '女性'), ('2', '男性')], max_length=1, verbose_name='性別')),
                ('yearly_income', models.IntegerField(verbose_name='年収(万円)')),
                ('height', models.FloatField(verbose_name='身長')),
                ('weight', models.FloatField(verbose_name='体重')),
            ],
        ),
    ]
